#!/bin/bash
# lp3 - lint Python 3 files
#
# Call flake8 and pylint one after another.
#
# author: andreasl

for file in "$@"; do
    printf '=== %s ===\n' "$file"
    printf 'Flake8 '
    flake8 --version
    flake8 --max-line-length 88 "$file"
    pylint --version | head -1
    pylint --msg-template='{msg_id} {path}:{line}: {msg}' "$file"
done
