#!/bin/bash
# lp3 - lint Python 3 files
#
# Call flake8 and pylint one after another.
#
# author: andreasl

printf 'Flake8 '
flake8 --version
flake8 --max-line-length 88 "$*"
pylint --version | head -1
pylint --msg-template='{msg_id} {path}:{line}: {msg}' "$*"
